language: php

php:
 - 5.4
 - 5.5
 - 5.6
 - hhvm

before_script:
 - composer self-update -n
 - composer install --dev -n

script:
# Issue with ocular.phar together with HHVM
 - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/phpunit --verbose --coverage-clover=coverage.clover; else php vendor/bin/phpunit --verbose; fi;
 - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then wget "https://scrutinizer-ci.com/ocular.phar"; fi;
 - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi;

matrix:
  fast_finish: true

notifications:
  email: false
